const data = [
  {
    id: "DHP75_122",
    name: "Getzial Matthew",
    email: "gxxxgmail.com",
    passportId: "A1234567",
    category: "Retrospective",
    type: "Pharmacists",
    appliedOn: new Date(2023, 6, 12),
    docVerified: "3/6",
    status: "Verified",
  },
  {
    id: "DHP15_784",
    name: "Sarah Thermoson",
    email: "sxxxgmail.com",
    passportId: "B9876543",
    category: "New",
    type: "Dentists",
    appliedOn: new Date(2023, 5, 10),
    docVerified: "3/6",
    status: "Irregular",
  },
  {
    id: "DHP75_124",
    name: "Robert",
    email: "rxxegmall.com",
    passportId: "B8613146",
    category: "Additional",
    type: "Dental Hygienists",
    appliedOn: new Date(2023, 8, 6),
    docVerified: "0/6",
    status: "In Progress",
  },
  {
    id: "DHP75_169",
    name: "Mahmoud Aziz",
    email: "jxxxgmail.com",
    passportId: "B6239567",
    category: "New",
    type: "Registered Nurses",
    appliedOn: new Date(2023, 6, 12),
    docVerified: "4/6",
    status: "Verified",
  },
  {
    id: "DHP15_784",
    name: "Haleema Docker",
    email: "hdgmail.com",
    passportId: "A28022001",
    category: "Retrospective",
    type: "Registered hygienists",
    appliedOn: new Date(2024, 2, 28),
    docVerified: "3/6",
    status: "Irregular",
  },
  {
    id: "DHP65_142",
    name: "Adil Changler",
    email: "axxegmall.com",
    passportId: "B09062001",
    category: "New",
    type: "Dental Hygienists",
    appliedOn: new Date(2024, 6, 9),
    docVerified: "6/6",
    status: "Rejected",
  },
  {
    id: "DHP65_152",
    name: "Ismaeel Builder",
    email: "ixxegmall.com",
    passportId: "C09062001",
    category: "Additional",
    type: "Dentists",
    appliedOn: new Date(2024, 12, 19),
    docVerified: "6/9",
    status: "Verified",
  },
];
export default data;
